name: GitHub Pages

on:
  push:
    branches:
    - maestros

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.15.0'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build:prod

    - name: Deploy
      # if: success()
      # uses: peaceiris/actions-gh-pages@v3
      uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from maestros,
        # also change the `maestros` in `refs/heads/maestros`
        # below accordingly.
      if: ${{ github.ref == 'refs/heads/maestros' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/exsodia
        enable_jekyll: true
